### ISSUE TITLE
Blocked Navigation Due to Eager Data Fetching

### ISSUE THREAD

**Issue by TeshaneCrawford** [zyyv/chris.me#62]
### Current Behavior

- Navigation is blocked until all data is loaded
- Uses `useFetch` which eagerly loads data on page load

### Expected Behavior

- Faster initial page load
- Navigation should not be blocked by data fetching

### Proposed Solution
Replace current `useFetch` implementations with `useLazyFetch`

```js
// Current implementation
const { data } = await useFetch('/api/repos')

// Proposed implementation
const { data } = await useLazyFetch('/api/repos')
```

### Potential Impact

- ✅ Improved navigation experience
- ⚠️ May require loading states to be handled properly

I'm willing to submit a PR implementing these changes if you agree with this approach

**Comment by zyyv** [comment]
Thanks for your attention and suggestions, if you are willing to send PR for improvement.

**Comment by TeshaneCrawford** [comment]
Instead of useLazyFetch I opted for removing "await" from the fetch call to display data on instant demand rather than waiting. Isssue #63
